development:
  secret_key_base: "this is not used anyway, just so rails won't raise any errors"
test:
  secret_key_base: "this is not used anyway, just so rails won't raise any errors"
production:
  secret_key_base: "this is not used anyway, just so rails won't raise any errors"
